### ISSUE TITLE
Get duration times for all transcripts

### ISSUE THREAD

**Issue by joyrexus** [ldp-uchicago/requests#13]
Ece would like a list of session lengths for all Period 1 ("Home") visits and toy sessions where available.

See current status of duration info [here](https://github.com/rcc-uchicago/ldp/blob/master/requests/ece/2014-11-10/README.md).

**Comment by joyrexus** [comment]
Reihonna and Teddy determined the spontaneous speech times for 234 additional transcripts.  See [status](https://github.com/rcc-uchicago/ldp/blob/master/requests/ece/2014-11-10/needed-durations/README.md).

**Comment by joyrexus** [comment]
The 234 duration times provided by Reihonna and Teddy were merged another list of needed durations times, resulting in a set of 289 duration times.  A [SQL update file](https://github.com/rcc-uchicago/ldp/blob/master/requests/ece/2014-11-10/update/update.sql) was generated and applied locally, to update the duration times in the LDP dataset's `transcripts` table (viz., the **minutes** column).  

We're still awaiting duration times on 11 transcripts (some of which still remain to be transcribed). See [current status](https://github.com/rcc-uchicago/ldp/blob/master/requests/ece/2014-11-10/update/README.md).

**Comment by joyrexus** [comment]
Updates were applied to LDP dataset master.  See #15.

**Comment by rwilliams04** [comment]
completed
