### ISSUE TITLE
Create Datavyu validation scripts

### ISSUE THREAD

**Issue by joyrexus** [ldp-uchicago/requests#20]
Use the Datavyu API to [create validation scripts](http://datavyu.org/user-guide/api/tutorials/check-for-coding-errors.html) that check for coding errors.  This will allow coders/transcribers to validate transcripts as they go.

See our [notes](https://github.com/rcc-uchicago/ldp/tree/master/requests/natalie/2015-01-08#notes) on the new column/code setup.

**Comment by rwilliams04** [comment]
completed
