### ISSUE TITLE
Extract worksheets from Cassie's excel files

### ISSUE THREAD

**Issue by joyrexus** [ldp-uchicago/requests#29]
Cassie Freeman sent a collection of excel files containing the utterances of the normally-developing subjects across all home visits (sessions 1-12). While doing some preliminary processing of these files I discovered that some of the files contain multiple worksheets with varying names.

For each excel file, we need to extract the appropriate worksheet (viz., the one containing the annotated utterances).

See details [here](https://github.com/rcc-uchicago/ldp/tree/master/requests/cassie/2015-04-24#2015-04-24).

**Comment by rwilliams04** [comment]
Completed
