### ISSUE TITLE
Handle Ece and Eliza's request

### ISSUE THREAD

**Issue by joyrexus** [ldp-uchicago/requests#35]
> From: Özlem Ece Demir <ecdemir@gmail.com>  
> Date: May 12, 2015  
> Subject: Fwd: number talk
>   
> Eliza and I started working on a project together. She informed me that you had pulled all the utterances for P3 parents and kids that include a number word.  All your previous correspondances are below. She then went through the utterances and identified those where number word is indeed used as such. The utterances are marked with `?` and/or `*`. 
>   
> Next, we would like to gather the number of word tokens in these utterances.  Would it be possible for you to pull out these for us, just like you did for Liz Gunderson? Would it be possible for us to get a count for `?` and `*` separately and also combined?

Details [here](https://github.com/ldp-uchicago/requests/tree/master/requests/ece/2015-05-15#2015-05-15).

**Comment by joyrexus** [comment]
[Done](https://github.com/ldp-uchicago/requests/tree/master/requests/ece/2015-05-15).

**Comment by joyrexus** [comment]
See Eliza's [follow-up email](https://github.com/ldp-uchicago/requests/tree/master/requests/eliza/2015-06-04#request).  Apparently Ece sent the wrong data file, so the report needs to be regenerated using the correct data file that was sent by Eliza.

**Comment by rwilliams04** [comment]
Completed [request](https://github.com/ldp-uchicago/requests/tree/master/requests/eliza/2015-06-04).

Best,
Richard
