### ISSUE TITLE
Pattern-based validation of Datavyu column/codes?

### ISSUE THREAD

**Issue by joyrexus** [ldp-uchicago/requests#40]
Natalie is wondering whether it's possible to do pattern-based validation of the column/codes in a Datavyu file.

It's possible to check the values of a column/code against a finite list of valid values with the [`checkValidCodes` function](http://datavyu.org/user-guide/api/tutorials/check-for-coding-errors.html), but the [Datavyu docs for the Ruby API](http://datavyu.org/user-guide/api.html) don't give any indication of how one might use regular expression patterns for validation.

We [posted a question regarding this](http://datavyu.org/support/questions/737/pattern-based-validation-of-columncode) to the Datavyu support forum.

**Comment by joyrexus** [comment]
See the [`ldp-uchicago/valid`](https://github.com/ldp-uchicago/valid) repo for an overview of how one could do pattern-based validation of the LDP columns using node/javascript.  This framework could of course still be used if the Datavyu transcript data were properly parsed and exported.  However, the advantage of using Datavyu's Ruby API is that such validation could be performed by a transcriber/coder in the course of doing their transcription and coding.

**Comment by joyrexus** [comment]
Nice! Someone in the support forum already provided a script that can be used for regexp-based validation along the same lines as the [`checkValidCodes`](http://datavyu.org/user-guide/api/tutorials/check-for-coding-errors.html) method.  Instead of passing in key/val pairs consisting of a code name (for key) and a list of valid values (for val), you'd pass in a regular expression for the val, e.g.:

`checkValidCodes2("myColumn", "", "aCode", Regexp.new('aPattern'), "bCode", Regexp.new('bPattern'))`

**Comment by rwilliams04** [comment]
Completed
