### ISSUE TITLE
Onset/offset validation in Datavyu?

### ISSUE THREAD

**Issue by joyrexus** [ldp-uchicago/requests#41]
Natalie is wondering whether it's possible to ensure that every cell contains an offset time greater than it's onset time.

Apparently [offset times are entered/triggered via the Datavyu controller](http://datavyu.org/user-guide/guide/tutorials/add-cells.html#add-cells-using-the-spreadsheet-menu).

A question was posed in the Datavyu support forum about automatically setting onset/offset times.  [An answer was provided with an accompanying ruby script](http://datavyu.org/support/questions/663/how-to-script-automatic-off-set-to-on-set-times) demonstrating how to iterate over onset/offset times for all cells in a column.  With a bit of experimentation I think this could be tweaked in order to check that any given cell's offset is greater than its onset time.

**Comment by rwilliams04** [comment]
Completed
